// MTE MK1 (la Churrera) v3.99.99 (final)
// Copyleft 2010-2017 by the Mojon Twins

// Generated by ene2h.exe from .\file.ene
// Copyleft 2010, 2017 by The Mojon Twins

typedef struct {
	int x, y;
	unsigned char x1, y1, x2, y2;
	char mx, my;
	char t;
#ifdef PLAYER_CAN_FIRE
	unsigned char life;
#endif
} MALOTE;

MALOTE malotes [] = {
 	{96, 32, 96, 32, 112, 32, 1, 0, 1},
 	{48, 80, 48, 80, 64, 80, 1, 0, 2},
 	{208, 16, 208, 16, 144, 96, -2, 2, 3},
 	{16, 16, 16, 16, 16, 96, 0, 2, 2},
 	{208, 112, 208, 112, 208, 32, 0, -1, 3},
 	{64, 32, 64, 32, 144, 112, 2, 2, 1},
 	{160, 16, 160, 16, 160, 128, 0, 2, 1},
 	{32, 32, 32, 32, 32, 80, 0, 2, 3},
 	{128, 80, 128, 80, 144, 80, 1, 0, 2},
 	{192, 16, 192, 16, 192, 128, 0, 2, 1},
 	{160, 48, 160, 48, 128, 48, -2, 0, 2},
 	{64, 80, 64, 80, 48, 80, -1, 0, 3},
 	{16, 32, 16, 32, 96, 32, 1, 0, 1},
 	{208, 96, 208, 96, 128, 96, -2, 0, 2},
 	{208, 32, 208, 32, 208, 64, 0, 2, 3},
 	{32, 16, 32, 16, 32, 128, 0, 2, 2},
 	{80, 16, 80, 16, 144, 80, 2, 2, 3},
 	{176, 48, 176, 48, 160, 48, -1, 0, 1},
 	{64, 32, 64, 32, 112, 32, 2, 0, 1},
 	{128, 80, 128, 80, 160, 80, 1, 0, 2},
 	{32, 16, 32, 16, 32, 96, 0, 2, 3},
 	{64, 16, 64, 16, 128, 80, 2, 2, 2},
 	{32, 96, 32, 96, 48, 96, 1, 0, 3},
 	{80, 128, 80, 128, 176, 128, 2, 0, 1},
 	{96, 16, 96, 16, 192, 96, 2, 2, 2},
 	{48, 32, 48, 32, 64, 32, 1, 0, 3},
 	{160, 96, 160, 96, 176, 96, 2, 0, 1}
};

#define N_ENEMS_TYPE_0 0
#define N_ENEMS_TYPE_1 9
#define N_ENEMS_TYPE_2 9
#define N_ENEMS_TYPE_3 9
#define N_ENEMS_TYPE_5 0
#define N_ENEMS_TYPE_6 0
#define N_ENEMS_TYPE_7 0

// This is output the way it worked originally, please modify if you need
// You may want to add type 5 or 6's below.
#define BADDIES_COUNT (N_ENEMS_TYPE_1+N_ENEMS_TYPE_2+N_ENEMS_TYPE_3)

typedef struct {
	unsigned char xy, tipo, act;
} HOTSPOT;

HOTSPOT hotspots [] = {
	{17, 1, 0}, 
	{114, 1, 0}, 
	{209, 1, 0}, 
	{18, 1, 0}, 
	{0, 0, 0}, 
	{211, 1, 0}, 
	{19, 1, 0}, 
	{119, 1, 0}, 
	{212, 1, 0}
};

#define N_HOTSPOTS_TYPE_0 1
#define N_HOTSPOTS_TYPE_1 8
#define N_HOTSPOTS_TYPE_2 0
#define N_HOTSPOTS_TYPE_3 0
#define N_HOTSPOTS_TYPE_4 0
#define N_HOTSPOTS_TYPE_5 0
#define N_HOTSPOTS_TYPE_6 0
#define N_HOTSPOTS_TYPE_7 0

